use customer_behaviour;
select *from shopping_trends;
select* from shopping_trends
Limit 10;

select count(*) from shopping_trends;

## what is the total revenue generated by male vs Female customers  ##
Select gender,sum(purchase_amount) AS Total_Revenue
From shopping_trends
Group by gender;

##  Which customer used discount but still spend more than the average purchase amount  ##
select customer_id,purchase_amount
From shopping_trends
where discount_applied = "yes" and purchase_amount>=(select avg(purchase_amount) from shopping_trends);

##  Which are the top 5 products with highest average review rating ##
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS Top_5_product_rating
FROM
    shopping_trends
GROUP BY item_purchased
ORDER BY Top_5_product_rating DESC
LIMIT 5;

## Compare the average purchase amounts between standard and express shipping ##
Select shipping_type, Round(Avg(purchase_amount),2)
From shopping_trends
where shipping_type in( "standard","express")
Group by shipping_type
order by avg(purchase_amount) desc;

## Do subcribed customers spend more? Compare average spend and total revenue between subcribers and non subcribers ##
select subscription_status, count(customer_id) As Total_customers,
avg(purchase_amount) As Avg_Spend, sum(purchase_amount) As Total_Revenue
From shopping_trends
group by subscription_status;

## Which 5 products have highest percentage of purchase with discounts applied? ##
select item_purchased,
(Round(sum(case when discount_applied = "yes" then 1 else 0 end)/count(*),2)*100) AS Discount_Rate
From shopping_trends
group by item_purchased
order by Discount_Rate desc
Limit 5;

## Are customers who are repeat buyers(More than 5 purchases) also likely to subscribe ##
Select subscription_status, 
count(customer_id) AS Repeated_customers
From shopping_trends
Where previous_purchases > 5
Group by subscription_status;

## Segment customers into New, Returning, loyal based on the total number of previous purchases , and show the count of each segment? ##
With customer_Type AS(
select customer_Id, previous_purchases,
case 
     When previous_purchases = 1 Then "New"
	 When previous_purchases between 2 and 10 Then "Returning"
     Else "Loyal"
     END AS Customer_Segment
From shopping_trends
)
 Select customer_segment, count(*) AS Number_of_Customers
 From customer_Type
 Group by customer_segment;
 
 ## What is the revenue contribution of each age group ##
Select age_group, sum(purchase_amount) AS Revenue
From shopping_trends
group by age_group
order by Revenue DESC;

 ## Which are the top 3 most purchased products within each category? ##
 With item_count AS(
 select category, item_purchased,
 count(customer_id) AS No_of_customers,
 Row_number() over(partition by category order by count(customer_id) DESC ) AS Item_Rank
 from shopping_trends
 group by category, item_purchased
 )
 select Item_Rank, Category, Item_purchased, No_of_customers
from item_count
where Item_rank<=3;

## What is the Most frequently used payment method ##
select preferred_pay_method, count(preferred_pay_method) As Most_Preferred 
From shopping_trends
group by preferred_pay_method
order by Most_Preferred DESC
limit 1;

## What is the Most frequently used payment method of each age group ##
Select age_group, preferred_pay_method, usage_count
from (
  select
     age_group, preferred_pay_method, count(*) AS usage_count,
     Rank() over(partition by age_group order by count(*)DESC) as Top_Rank   
  from shopping_trends
  group by age_group, preferred_pay_method
  )Ranked
Where Top_Rank =1
order by usage_count DESC;

## what is the Top 3 payment method for each age group? ##
Select age_group, preferred_pay_method, usage_count
from (
  select
     age_group, preferred_pay_method, count(*) AS usage_count,
     Rank() over(partition by age_group order by count(*)DESC) as Top_Rank   
  from shopping_trends
  group by age_group, preferred_pay_method
  )Ranked
Where Top_Rank <=3
order by age_group, usage_count DESC;

 ## What is the most purchased item by each location ##
 select location, item_purchased As Most_purchased, Total_sales
 From(
	  Select location, item_purchased, count(*) As Total_sales,
      Rank() over(partition by location order by count(*) DESC) AS Item_Rank
      From shopping_trends
      group by location, item_purchased
      )Ranked
 Where item_Rank = 1
 order by location;
 
 ## Which is the top selling products in each season ## 
  Select season, item_purchased As Most_selling_item, Total_sales
  From( 
       Select season, item_purchased, count(*) AS Total_sales,
       Rank() Over(partition by season order by count(*) Desc) AS rn
       FRom Shopping_trends
       group by season , Item_purchased
       )Ranked
       Where rn = 1
       Order by season, Most_selling_item DESC;